name: miracle
channels:
 - conda-forge
dependencies:
 - matplotlib=3.0.2
 - pylint=2.2.2
 - python=3.6
 - scikit-learn=0.20.2
 - tesseract=4.0.0
 - tensorflow-gpu=1.12.0
 - pip:
    - opencv-python==4.0.0.21
    - pytesseract==0.2.6
    - requests==2.21.0
    - selenium==3.141.0